version: '3.8'

services:
  device-service:
    build: .
    container_name: loqa-device-service
    environment:
      - NATS_URL=nats://nats:4222
      - LOG_LEVEL=info
    depends_on:
      - nats
    networks:
      - loqa-network

  nats:
    image: nats:2.10-alpine
    container_name: loqa-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["nats-server", "-js", "-m", "8222"]
    networks:
      - loqa-network

networks:
  loqa-network:
    driver: bridge